name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python: [3.4, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        python-version: ${{ matrix.python }}
    - name: pip
      run: python3 -m pip install pybind11 setuptools wheel
    - name: make
      run: make -j8
    - name: sdist
      run: python3 setup.py sdist
    - name: install
      run: python3 -m pip install dist/*.tar.gz
    - name: test
      run: cd ../ && python3 -c 'import simplecache'
    - uses: actions/upload-artifact@v2
      with:
        name: simplecache
        path: |
          dist/*
